from __future__ import annotations

import multiprocessing as mp
import numpy as np

from loguru import logger
from pathlib import Path
from tqdm import tqdm

from simple_scenario import Scenario, EgoConfiguration, Vehicle
from simple_scenario.road import SyntheticRoad, StraightSegment


class CutOutScenarioGenerator:
    """
    Create cutout scenarios based on definiton in UNECE R157 E/ECE/TRANS/505/Rev.3/Add.156/Amend.4, Annex 3, pp. 53-55
    """

    def __init__(self, result_dir: str | Path | None = None) -> None:
        self._result_dir = result_dir

        # Parameters listed in Table 2 on page 43
        self._n_lanes = 2
        self._lane_width = 3.5
        self._min_road_length = 400
        self._ego_s0 = 100
        self._ego_t0 = 0
        self._ego_lanelet_id = 1001
        self._object_lanelet_id = 1001
        self._thw0 = 2
        self._f_lanelet_id = 1001
        self._vf0 = 0

        # Varying values
        vy_min = 0
        vy_max = 3
        dx0_f_min = 0
        dx0_f_max = 100
        # Vary
        vy_step = 0.1
        dx0_f_step = 1
        self._vy_values = np.arange(vy_min + vy_step, vy_max + vy_step, vy_step)
        self._dx0_f_values = np.arange(dx0_f_min, dx0_f_max + dx0_f_step, dx0_f_step)

        # Parameters per plot
        ve0_kmh_values = [60, 50, 40, 30, 20, 10]

        n_plots = len(ve0_kmh_values)
        self._params_per_plot_no = {
            i + 1: {"ve0_kmh": ve0_kmh_values[i]} for i in range(n_plots)
        }

    def create_all_scenarios(
        self,
        result_dir: str | Path | None = None,
        only_plot_no: int | None = None,
        create_openx: bool = False,
        create_image: bool = False,
        create_gif: bool = False,
    ) -> None:
        if result_dir is None:
            if self._result_dir is None:
                msg = "self._result_dir is None. Therefore, you need to specify a result_dir when calling create_all_scenarios."
                raise RuntimeError(msg)
            result_dir = self._result_dir

        self._result_dir = Path(result_dir)
        self._result_dir.mkdir(exist_ok=True)

        for plot_no, params in self._params_per_plot_no.items():
            if only_plot_no is not None and plot_no != only_plot_no:
                continue
            self._create_scenarios_of_plot_no(
                plot_no,
                **params,
                create_gif=create_gif,
                create_image=create_image,
                create_openx=create_openx,
            )

    def get_single_scenario_lcd_thw(
        self,
        scenario_name: str,
        ego_v0: float,
        ego_thw_lead0: float,
        lead_lc_duration: float,
        lead_thw_f0: float,
        vf0: float,
        check_collision_feasibility: bool = True,
    ) -> Scenario | None:
        # Distance between ego and lead
        dx0_ego_lead = ego_v0 * ego_thw_lead0

        # Distance between lead and f vehicle (assumption ego and lead share same speed)
        dx0_lead_f = ego_v0 * lead_thw_f0

        return self._create_single_scenario(
            dx0_f=dx0_lead_f,
            vy=None,
            ve0=ego_v0,
            dx0_ego_lead=dx0_ego_lead,
            lc_duration=lead_lc_duration,
            vf0=vf0,
            scenario_name=scenario_name,
            check_collision_feasibility=check_collision_feasibility,
        )

    def get_single_scenario(
        self,
        dx0_f: float,
        vy: float,
        ve0: float,
        check_collision_feasibility: bool = True,
    ) -> Scenario | None:
        """
        Get a single scenario generated by the given parameter values (None if 'check_collision_feasibility' is True and the scenario is not feasible)
        """
        return self._create_single_scenario(
            dx0_f=dx0_f,
            vy=vy,
            ve0=ve0,
            check_collision_feasibility=check_collision_feasibility,
        )

    def _create_scenarios_of_plot_no(
        self,
        plot_no: int,
        ve0_kmh: float,
        create_openx: bool = False,
        create_image: bool = False,
        create_gif: bool = False,
    ) -> None:
        # Create folders
        plot_no_result_dir = self._result_dir / f"plot_{plot_no:02d}"
        plot_no_result_dir.mkdir(exist_ok=True)

        # Each scenario will get its own subfolder under the plot directory

        ve0 = ve0_kmh / 3.6

        n_scenarios = len(self._dx0_f_values) * len(self._vy_values)

        with tqdm(total=n_scenarios, desc=f"Plot No. {plot_no}") as progress_bar:
            for dx0_f in self._dx0_f_values:
                for vy in self._vy_values:
                    self._create_single_scenario(
                        dx0_f=dx0_f,
                        vy=vy,
                        ve0=ve0,
                        plot_no=plot_no,
                        plot_no_result_dir=plot_no_result_dir,
                        create_gif=create_gif,
                        create_image=create_image,
                        create_openx=create_openx,
                    )
                    progress_bar.update(1)

    def _create_single_scenario(  # noqa: PLR0912
        self,
        dx0_f: float,
        vy: float,
        ve0: float,
        dx0_ego_lead: float | None = None,
        lc_duration: float | None = None,
        vf0: float | None = None,
        scenario_name: str | None = None,
        check_collision_feasibility: bool = True,
        plot_no: int | None = None,
        plot_no_result_dir: str | Path | None = None,
        create_gif: bool = False,
        create_image: bool = False,
        create_openx: bool = False,
    ) -> Scenario | None:
        ve0_kmh = ve0 * 3.6
        ve0_kmh = int(np.round(ve0_kmh))

        if dx0_ego_lead is None:
            dx0_ego_lead = dx0_f

        if vf0 is None:
            vf0 = self._vf0

        plot_no_str = ""
        if plot_no is not None:
            plot_no_str = f"_plot_{plot_no:02d}"

        if scenario_name is None:
            scenario_name = (
                f"cutout{plot_no_str}_ve0_{ve0_kmh}_dx0f_{dx0_f:.1f}_vy_{vy:.1f}"
            )

        # Create simple scenario object
        ego_configuration = EgoConfiguration(
            self._ego_lanelet_id, self._ego_s0, self._ego_t0, ve0
        )

        # Calculate lc_duration, TODO: USE lc_duration if not None; and calculate vy from that
        if lc_duration is None:
            object_vehicle_lc_duration = self._lane_width / vy
        else:
            object_vehicle_lc_duration = lc_duration
            vy = self._lane_width / object_vehicle_lc_duration
        scenario_duration = np.ceil(object_vehicle_lc_duration) + 10

        dummy_vehicle = Vehicle(0)
        # Object vehicle
        dx0 = ve0 * self._thw0
        if dx0_ego_lead is not None:
            dx0 = dx0_ego_lead
        object_vehicle_s0 = (
            self._ego_s0 + dx0 + ego_configuration.length / 2 + dummy_vehicle.length / 2
        )
        object_vehicle_t0 = self._ego_t0
        vo0 = ve0
        object_vehicle = Vehicle(
            0,
            start_lanelet_id=self._object_lanelet_id,
            start_s=object_vehicle_s0,
            start_t=object_vehicle_t0,
            v0=vo0,
            lc_direction=-1,
            lc_type="vy",
            lc_vy=vy,
        )

        # f vehicle (slow vehicle)
        f_vehicle_s0 = object_vehicle_s0 + dummy_vehicle.length + dx0_f
        f_vehicle_t0 = object_vehicle_t0
        f_vehicle = Vehicle(
            1,
            start_lanelet_id=self._f_lanelet_id,
            start_s=f_vehicle_s0,
            start_t=f_vehicle_t0,
            v0=vf0,
        )

        # Calculate road length
        ego_dist = ve0 * scenario_duration
        road_length = (
            max(ego_dist, self._min_road_length) + self._ego_s0 + 110
        )  # TODO(STA): check length of object trajectory as well
        goal_position = max(
            self._ego_s0 + 0.75 * ego_dist,
            f_vehicle_s0 + vf0 * scenario_duration + dummy_vehicle.length,
        )
        ego_configuration = EgoConfiguration(
            self._ego_lanelet_id,
            self._ego_s0,
            self._ego_t0,
            ve0,
            target_s=goal_position,
            target_t=0,
            target_lanelet_id=self._ego_lanelet_id,
        )
        road = SyntheticRoad(
            self._n_lanes,
            self._lane_width,
            segments=[StraightSegment(road_length)],
            speed_limit=60,
        )

        vehicles = [object_vehicle, f_vehicle]
        scenario = Scenario(
            scenario_name,
            road,
            ego_configuration,
            vehicles=vehicles,
            duration=scenario_duration,
            check_feasibility=False,
        )

        scenario_is_feasible = True
        if check_collision_feasibility and not scenario.is_feasible(
            check_trajectories=False, check_collision=True
        ):
            scenario_is_feasible = False

        if not scenario_is_feasible:
            return None

        if plot_no_result_dir is not None:
            scenario_dir = Path(plot_no_result_dir) / scenario_name
            scenario_dir.mkdir(exist_ok=True)

            scenario_config_dir = scenario_dir / "configs"
            scenario_config_dir.mkdir(exist_ok=True)
            scenario.save(scenario_config_dir)

            if create_openx:
                scenario_openx_dir = scenario_dir / "openx"
                scenario_openx_dir.mkdir(exist_ok=True)
                scenario.save(scenario_openx_dir, mode="openx")
            if create_image or create_gif:
                scenario_image_dir = scenario_dir / "images"
                scenario_image_dir.mkdir(exist_ok=True)
            if create_image:
                scenario.render(scenario_image_dir, dpi=600)
            if create_gif:
                scenario.render_gif(scenario_image_dir, dpi=600)

        return scenario


def unpack_and_run(args_list: list) -> None:
    scenario_generator = CutOutScenarioGenerator(args_list[0])
    scenario_generator.create_all_scenarios(
        only_plot_no=args_list[1],
        create_image=args_list[2],
        create_openx=args_list[3],
        create_gif=args_list[4],
    )


def generate_all_scenarios() -> None:
    result_dir = Path(__file__).parent / ".." / "results" / "annex3" / "cutout"
    result_dir.mkdir(exist_ok=True, parents=True)

    create_image = True
    create_openx = True
    create_gif = False

    n_plots_in_regulation = 6

    n_workers = n_plots_in_regulation

    all_args_lists = [
        [result_dir, i + 1, create_image, create_openx, create_gif]
        for i in range(n_plots_in_regulation)
    ]

    if n_workers == 1:
        for arg_list in all_args_lists:
            unpack_and_run(arg_list)
    else:
        with mp.Pool(n_workers) as pool:
            result_iterator = pool.imap(unpack_and_run, all_args_lists, chunksize=1)
            for _ in result_iterator:
                pass
    logger.info("done")


if __name__ == "__main__":
    generate_all_scenarios()
